# -*- coding: utf-8 -*-
"""complete_task_1.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tBi1a19n3HKCACgV2XbaHIbZp1HB10r6
"""

my_favorite_songs='Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation'

print(my_favorite_songs[:14] + my_favorite_songs[-14:]+my_favorite_songs[15:30]+my_favorite_songs[-27:-15])